### PR TITLE
Mobilenav

### PR DESCRIPTION
**Pull request by nachiketkumar**
##### Goals
- In this branch, I want to get the nav almost finished:
  - I removed the margins that were being applied when `.nav-open` was added from the `body` and applied to the `.main` div.
  - Set up the mobile nav structure. Resize the page to see this in action. The text that says Header needs to change based on what page you're on- basically it should have the same text as the navigation link. So if you are editing a classroom or adding students, the top header should say Classroom, again to show the user where in the app they are. Right now the code is in `application.html.erb` but should probably go into a partial- help here would be good.
  - The text that says 'Help Toggle' on the right is where the help toggle icon will go for students and requesters icon for the teachers. I could use some help with conditional code to set this up- just add empty divs for now.
- The final remaining part in the nav, which will be the next thing I work on, is the subnav for the account link. We talked about it showing on hover. I think there could be easier solutions:
  - Add a logout icon to the menu. Clicking on account would open another slideout nav to the right. This would have the name of the user, user role, edit profile and any other relevant links (help? contact us? billing etc later on). OR
  - Add a logout icon to the menu. Clicking on account takes you to the edit profile page, showing you the users name and user role with a subnav on the page for the other subnav links (help, contact etc). This 2nd option would be easier to implement, and since the main part of the account really is the edit profile right now, it should be OK.
##### Issues:
- When in mobile view, clicking the burger icon opens the menu fine, but the menu remains open when you click any of the nav items. I think this has to do with the local storage. The correct behavior should for the menu to close again when something is clicked/tapped.

### CODE REVIEW

**Comment by aomran** [comment]
Nachi, can you explain the behaviour that you're going after for desktop and mobile separately. Also I believe scrolling is disabled now. Go to an analytics page to see what I mean.

**Comment by aomran** [comment]
After using it a bit longer, I feel I get the idea. The only problem is that the nav should by default always be collapsed. Scrolling issue is still there.

**Comment by aomran** [comment]
So we can for example only enable the localStorage saving of the nav options with the bigger window sizes. This would be done by using [Window.matchMedia](http://caniuse.com/matchmedia). This doesn't work for IE 8 & 9. If we want to support IE9 then there's a [polyfill](https://github.com/paulirish/matchMedia.js) (<2kb). If we want to support IE6-8 then there's another [polyfill](https://github.com/knightdr/media-match) although it's older and bigger (~3kb).

What kind of support are we going for?

**Comment by nachiketkumar** [comment]
So on desktop, the nav should be like we've been seeing it: default expanded and collapsible.

On mobile, the nav is totally hidden by default. When the mobile nav button is clicked, it opens the expanded form. There is no collapsed form for mobile. On clicking any link in the nav when it is opened in mobile view, the nav should disappear again.

Does this help?

**Comment by nachiketkumar** [comment]
I don't see the UIoptions/local storage as a critical feature for the app. If we support IE9+, I think we should be safe given our initial target market. <IE8 shouldn't be an issue anyway because the Window.matchMedia fix is really for mobile views correct? I don't even know what, if any, use of IE is on mobile.

**Comment by aomran** [comment]
Ok when I get back i'll implement this. So UiOptions will be enabled for bigger window sizes and IE9+. I'll include the polyfill from Paul Irish.

**Comment by aomran** [comment]
The `current_page_header` helper is a bit ugly but I cant think of a better way at the moment. Everything else should be in place. If you need anything else then let me know. As for the account link, I think going for the easier path is best. Maybe the account icon can indicate the teacher/student role somehow. The code would be simple to implement:

```
<span class="nav-label">Account</span>
```

replaced with

```
<span class="nav-label <%= current_user.classrole_type %>">Account</span>
```

The `classrole_type` would give you either `teacher` or `student` as a class name. Not sure how difficult the icon making is though.

**Pull request merged**
