### PR TITLE
start analytics view styling, implement students show toggle

### PR DESCRIPTION
**Pull request by nachiketkumar**
Styling the analytics view for the teachers here.
- main part of analytics view is styled. toggle works and shows students that haven't voted for all checkpoints.

### CODE REVIEW

**Comment by nachiketkumar** [comment]
- I need some help with resolving a small issue. removed the header from `analytics_helper.rb` and put in `_checkpoint.html.erb`, didn't see why it needed to be in the helper? Also, does  the `div.hasn't-voted` need to be in the helper? I've commented it out in the partial, and would prefer it in the partial. EDIT: I uncommented it here for the show/hide toggle to work properly.
- I added a span for each name but need to add the class `.student-not-voted` to this span (couldn't figure out how). I used pseudo selector `:after` to add a comma to each name but the last one.

**Comment by aomran** [comment]
Let me know if this commit solves the issues. The `div.hasnt-voted` doesn't need  to be in the helper.

**Comment by nachiketkumar** [comment]
I did some more styling, question:
- Is the hover on the toggle too much? I did want to call attention to it as it might get lost otherwise. Also thought about whether the background color should be the warning color in order to indicate that this removes some privacy/anonymity.
- The toggle action is working but you might have to refactor a little more and move some stuff back into the helper. As it stands, the div is showing even if there are no students. So only the title shows. The div should show only if there are students in the list.
- I'm using the same `.hasnt-voted` class to toggle the little explanation div. Do you think this div is necessary? It can be confusing in demos with small class sizes because it doesn't explain it fully. Don't worry about the show/hide, if in the process of fixing the previous step this stops working I can use different classes to toggle it.

**Comment by aomran** [comment]
An alternative approach is to only show the "eye" icon and the "Show students that haven't voted" text when there is something to show for that specific checkpoint. A tooltip can say "This feature is enabled when < 25% of the class hasn't voted.". The eye + text can be placed right under the bars, i.e. where the STUDENTS THAT HAVEN'T VOTED: shows up now.

This way the UI only shows up when appropriate and since it's something "new", a tooltip explains why all of a sudden the teacher is seeing it. Toggling per checkpoint makes sense since you don't really know how many checkpoints qualify.

**Comment by aomran** [comment]
Or put the icon+text in the sidebar with the phasing options. Explaining when it's enabled and clicking it opens up all `div.hasnt-voted` but we'll make sure that this div isn't added if there is nothing to show.

**Comment by aomran** [comment]
So I kept your implementation Nachi, just moved all of the markup for the hasnt-voted box into the helper. This means the `div.hasnt-voted` only shows up for the valid checkpoints.

**Comment by aomran** [comment]
Suggestion: reword "toggle students that haven't voted" to "show students that haven't voted" since that seems like more natural wording. Most show actions are also hide actions when clicked a second time. Or say "show/hide". And "ONLY SHOWS FOR CHECKPOINTS WHERE > 75% OF THE CLASS HAS VOTED." to "ONLY SHOWS FOR CHECKPOINTS WHERE < 25% OF THE CLASS HAS NOT VOTED."

**Comment by aomran** [comment]
Bug: the edit track page has a weird rending issue. The date and time picker gets cut off at the bottom.

**Comment by nachiketkumar** [comment]
Thinking more about this view, which is a very important one to get right, I find the layout confusing. It's not obviously clear what the phasing is related to- the list of checkpoints on the page or the sidebar links? To us it is obvious but I can imagine it being confusing to a new user.
- One option is to move this select into the div where the student show/hide toggle is currently to show a more clear relationship with the checkpoints in this list.
- Make the student show hide into just an icon that is in line with the expectation title as described above by Ahmed, and make it toggle per checkpoint, not globally.
- I would like to get rid of the 'Choose Phase' button entirely, and make the select links also work as submits- too complicated? So when you choose a phase it does what clicking the button would have done. It would make the styling easier and to me is intuitive. Default can still be realtime.

**Comment by aomran** [comment]
I put the button inside `<noscript>` tags but that's completely optional. If we're comfortable not having this feature for  js-disabled browsers then delete the button. The form now submits on select change.

**Comment by aomran** [comment]
Everything up to this point has been checked so merge whenever unless you still want to work on the analytics view some more.

**Comment by nachiketkumar** [comment]
I'm almost done with this branch, still want to do what I mentioned in the last comment w/bullets, wrt position of phase selector and show students toggle. That and fixing what I somehow broke, and this should be good to be merged sometime tomorrow.

**Comment by aomran** [comment]
Looks like JavaScript got messed up because the indenting for some reason was off a bit in the coffee-script file. All fixed now (I think).

**Comment by nachiketkumar** [comment]
yup works now!

**Comment by aomran** [comment]
In airport atm, this commit should do what you need.

**Comment by nachiketkumar** [comment]
Thanks ahmed! This is good to go. minimal styling remaining on the app, we can focus now on getting people to use it and insights gained from mixpanel.

**Pull request merged**
