### PR TITLE
Ajaxmodal

### LINKED ISSUE #125: Long track titles messing up grid
Implement the change that Nachi suggested for ending long track names with `...` to not mess up the grid.

### PR DESCRIPTION
**Pull request by aomran**
Very much a work on progress but so far I have the "add classroom" modal working through AJAX. The "join classroom" modal works but through regular http not AJAX (although it's still fast).

Validations need to also happen through AJAX so what I'm doing right now is:
1. Adding a class called `error` to the input field where the error occurred
2. Prepending the validation error to the input.

resolve #125

### CODE REVIEW

**Comment by nachiketkumar** [comment]
do we need a close link as well as the close icon? Looks good by the way, I don't think I need to do much for styling yet. Can the modal background extend over the top and nav as well?

**Comment by aomran** [comment]
I don't actually see the close icon for some reason and I have no idea why the background doesn't cover everything.

**Comment by aomran** [comment]
So the adding and joining a classroom is now fully done through ajax and a modal. If a validation error occurs then the input field gets a class of `error` and a `span.error-message` is created and prepended to the input field. If the request is successful then the modal closes and the classroom appears right away on the page.

The next step is to pretty much repeat the exact same thing for checkpoints.

**Comment by aomran** [comment]
I'm going a bit crazy with the truncate so if this looks really weird then lets remove it. The grid just breaks in weird ways and makes the app look pretty bad. The title, active/unpublished badges, start/end times are on the next "show" page so the truncated stuff isn't just in that place.

**Comment by pjfranzini** [comment]
So I tried to actually add a 300 char long checkpoint, and I got a
"value too long for type character varying(255)"
error. So I guess we should back down to 255char checkpoint max -- or perhaps 250, to not be smack up against the data base limit

**Comment by pjfranzini** [comment]
We may need a different solution for the grid. Right now the grid is still fairly breakable by, for example, having classroom descriptions of different lengths (on standard screen sizes, classroom descriptions may be 0, 1 or 2 lines long). Sometimes this breaks the grid, sometimes not. Meanwhile, long track titles that are truncate are breaking the display of the unpublished/active labels....

**Comment by aomran** [comment]
So this concludes the "Adding classrooms and checkpoints through AJAX" story as far as I see. Let's merge this once everyone has had a look and once Nachi has had some time to do a tiny of bit of styling (mostly just the form error message).

**Comment by aomran** [comment]
Summary of what was done.
- Create Classroom modal
- Join Classroom modal
- Add Checkpoint modal
- Modals should give validation errors
- Fixed classroom and tracks grid (using truncate)
- Classroom id is added to teacher/student help events
- Student Gravatars on requesters page
- Required form inputs have a *
- Teachers now required to include first/last name.
- Track end_time set to end_of_day if no time is provided.

This is ready to be merged after a final visual check from Paula and/or Ali.

**Comment by pjfranzini** [comment]
— since there is nothing wrong with reusing a teacher token to rejoin a classroom (if you leave it first)
I changed "You have already used this token”  error message to a
"You are already in this classroom” error message

— found it strange that there was a limit on Classroom Description length but not on Classroom name length so implemented a limit there too. Since it’s not an expandable text box, followed Ahmed’s advice that it was not necessary to specify the limit in the placeholder text.

— Changed various “Are you sure” popup messages to be more specific

to work on: losing lozenges on long titles

— fixed a bug that was not only keeping Classroom id from being added to teacher help events but was keeping teacher help events from tracking at all

— fixed (with help!) a bug that was keeping the gravatar images from actually appearing on the help page (the current user’s gravatar would be used over and over instead of each requester’s)

— comment: In Edit profile, none of the fields are required really (they are starred)

— Edit Checkpoint bug noted, Ahmed fixing

**Comment by pjfranzini** [comment]
Yeah it makes sense to me now.

**Comment by pjfranzini** [comment]
But then things like New Classroom Name in Edit classroom should have the star too
Since you cant delete the old name and update the classroom

**Comment by pjfranzini** [comment]
Ok finished with visual check, but will recheck after a couple more things Ahmed is working on.

**Pull request merged**
