### PR TITLE
Work on Tracks View

### PR DESCRIPTION
**Pull request by aomran**
Work on a few pivotal tracker stories here that are related to track views.

### CODE REVIEW

**Comment by aomran** [comment]
So for styling you would work with `today-track` on index page and `highlight` for show sidebar. Of course change them to w/e you want.

**Comment by aomran** [comment]
The tracks are sortable now too. You can add a placeholder class if you want to style it like you did with the checkpoints.

**Comment by aomran** [comment]
Active track now means:
- `start_time` is in the past or now
- `end_time` is in the future or now
- track is `published`

**Comment by aomran** [comment]
So from now on a Gravatar url will be generated every-time a user saves their profile (or creates an account). We can use this url anywhere in the app. The url is stored in the database so that we don't have to create it every-time the gravatar is needed.

To update the existing users run `$ rake curri:add_gravatars`.

**Comment by aomran** [comment]
So still to be done before the branch can be merged:
- [x] Visual review of "Add day of the week to a track"
- [x] Visual review of "Active track should be highlighted on the track's index view."
- [x] Visual review of "Highlight current track on sidebar"
- [x] Visual review of "Teachers should be able to order tracks in the index view."
- [x] Finish adding Gravatars to app (on nav?)
- [x] Finish add styling to the note editor & visual review of track note.

**Comment by pjfranzini** [comment]
So I did an overall visual check. Very impressive work (and amazing pivotal velocity :) )

I thought it weird to be able to put as much track note as one please but only see 2 lines of it, so Ahmed made the box bigger. It is a pity that it doesn't give us the enlarge box handle.

**Pull request merged**
