### PR TITLE
Subnav

### PR DESCRIPTION
**Pull request by nachiketkumar**
Created a new subnav branch for a couple of minor issues:
- Restyled the colors of the subnav- the previous one was looking too dark and messy.
- Minor style changes
- Separated the styles into a navigation module
##### Issues
- For some reason, after I did this (the last step- separating into a module), the JS for toggling the `.subnav-open` and `.subnav-show` for `.main` and `.subnav` respectively isn't working correctly. The classes get added for a fraction of a second and then automatically removed. I couldn't figure out why this was happening- any clue?
- Also, it would be nice to be able to resolve the other problem that I haven't been able to solve in this branch. The `.fixed-nav` has a `min-height: 465px;` to avoid the bottom div from overlapping the analytics link in landscape mobile view. However, this causes the bottom div to get cut off, and I can't figure out how to make the navbar be scrollable, so that part of the navigation gets hidden. Does this make sense?

### CODE REVIEW

**Comment by aomran** [comment]
I believe the commit that I just made fixes the first issue. This is a classic problem, if you use a link to do things on the page then you need to prevent the default action (which is a browser refresh).

**Comment by aomran** [comment]
To be clear, the problem started when you switched the link's href from `'#'` to `''`. The `#` means go to the top of the page, so the page isn't refreshed. The empty string by default does a refresh. The previous implementation (one with #) isn't good either since if someone is at the bottom of the page they'll be bumped to the top.  So I guess the best practice is to always use `e.preventDefault` for these kinds of things.

**Comment by nachiketkumar** [comment]
Great, thanks for the explanation. Would a different element (not a link) be better used here? My thought is to leave it as it is now with the `e.preventDefault`.

Paula, do you want to take a shot at figuring out the second issue? We can then merge this branch. It's not critical though.

**Comment by nachiketkumar** [comment]
I decided to merge this into master, the remaining issue can be pushed separately if someone can figure it out.

**Comment by aomran** [comment]
To answer your previous question: I think that a link should be used to be semantically correct.

**Pull request merged**
