### PR TITLE
seperated the rating buttons ajax into its own file and decoupled it fro...

### PR DESCRIPTION
**Pull request by aomran**
Originally the student view was also listening to the websocket channel. This doesn't make a whole lot of sense. I went ahead and just separated that. Now the student view only updates when they click a button. 

Paula can you test this?

### CODE REVIEW

**Comment by pjfranzini** [comment]
It goes boom. Near as I can tell, this is because your branch has an old version of a view:https://github.com/aomra015/curry/blob/ratingwebsocketbug/app/views/shared/_header.html.erb(good versionhttps://github.com/aomra015/curry/blob/master/app/views/shared/_header.html.erb)so I get a "NoMethodError in Classrooms#index"pretty much right off the bat.

**Comment by aomran** [comment]
I merged changes from master. Sorry I should have done that before branching.

**Comment by pjfranzini** [comment]
It seems to work fine (and fix the bug). I can't say I understand the code though. Do you want me to ok it as functions fine, or do you want to first go over it a few minutes with me when you get home?

**Comment by aomran** [comment]
I can run through the code with you of course but what I need is manual testing to make sure that it works as expected. i.e. users can vote, votes get updated but if two students are logged on then they shouldn't affect each other (the stuff we were seeing this morning).

**Comment by pjfranzini** [comment]
yes, I verified that, that is what "It seems to work fine (and fix the bug)" means. I even reverified the existence of the bug in the pulled master just before, as a control step.

**Comment by aomran** [comment]
Ok great. We can go over the code later.

**Comment by pjfranzini** [comment]
Actually I spoke too soon. I tested it with two students, and that was good (each student sees their own update refresh immediately, and is not affected by their neighbor's revote). However after you asked me again, I realized that I hadn't tried one teacher one student. Indeed, teacher no longer sees live update of analytics, must refresh to get updated bars.

**Comment by aomran** [comment]
It should be fixed now.

**Comment by pjfranzini** [comment]
Looks good.

**Pull request merged**
