### PR TITLE
Delayedjob

### PR DESCRIPTION
**Pull request by aomran**
Emails take a while to send so it's a best practice to do them in a "background process" meaning that instead of waiting for emails to be sent before responding to the user, the app responds immediately then gets another "server" to take care of the emails on the side.

Delayed Job was created by Tobi to do this kind of stuff for Shopify. In this branch I'm queueing the invitation emails, password reset emails and hopefully email reminder emails into a queue that gets processed outside of our app. 

I signed us up for HireFire, 30 day trial and then $10/month so that we avoid having to pay $35/month for a Heroku worker. Hirefire will check every few seconds to see if there's anything in the delayed job queue, if there is then it will bump our worker dyno up to 1, process the queue and then turn it off. Heroku charges cents per hour so it saves money.

To start the app just run `$ foreman start` from now on instead of `$ rails s` because we need delayed job running alongside our app in development.

### CODE REVIEW

**Comment by aomran** [comment]
If you're testing the mailers you should notice that the password reset one will not work properly for the teachers. That's because we now require first/last name but your data might be using old seed data which doesn't have those. Without a first/last name the password reset will give validation errors when it tries to save the password reset token to the user model.

**Comment by aomran** [comment]
This last commit adds a gem that will be enabled by default in Rails 4.1. Go to `http://localhost:3000/mail_view` to see a preview of the emails that go out. This way we can see how they look without needing to do anything special in development.

**Comment by nachiketkumar** [comment]
Considering that we are not implementing email reminders right now, perhaps this branch could be merged. `Delayed  Job` is set up, email reminders would be a new branch if it came time for it?

**Comment by aomran** [comment]
Yeah sometime today I'll merge this and make sure hirefire is working properly.

**Pull request merged**
