### PR TITLE
Refactors

### PR DESCRIPTION
**Pull request by aomran**
Some stuff I was working on in the airplane. This branch was two branches: "refactorModels" & "refactorControllers".

### CODE REVIEW

**Comment by nachiketkumar** [comment]
Can I ask for a clearer flash message if a teacher tries to add the same classroom again by using the same token? Currently I think we have the notice saying 'invalid token,' which I guess you could argue is correct, but I think a clearer message would be 'You have already used this token' or something to that effect. So if the teacher accidentally leaves the class but still has the token, they can always get back in.

**Comment by aomran** [comment]
So to write some pseudocode for my suggestion above:

```
def hasnt_voted(phase, classroom)
  if no_ratings || (numb_ratings < numb_students*0.75)
    false
  elsif numb_ratings == numb_students
    "all"
  else
    list_names_of_students_who_havent_voted
  end
```

Then in the view helper if we get `false` then we just don't create this "hasn't voted box". If we get "all" then maybe build some indicator that everyone has voted. 

In a classroom with 25 students. If 75% or more (19+) of the students voted then we list out the students who haven't voted (which should be a small list unless we're talking about a classroom with hundreds of students).

So the end result is that in most situations, teachers will not see an indication of who hasn't voted. In the situations where only a small percentage of students haven't voted then we aid them in finding out who hasn't. In the "success" case, i.e. all students voted then we display some indicator of success.

**Comment by nachiketkumar** [comment]
Should we worry about cases where all have voted? Wouldn't that be clear enough from the progress bar being 100% filled?

**Comment by aomran** [comment]
Good point.

**Comment by aomran** [comment]
So modified:

```
def hasnt_voted(phase, classroom)
  if no_ratings || (numb_ratings == numb_students) || (numb_ratings < numb_students*0.75)
    false
  else
    list_names_of_students_who_havent_voted
  end
end
```

So in most situations the method will return `false`. The view helper can check for "truthyness" and only build markup when it gets an array back with names.

**Comment by nachiketkumar** [comment]
Yes. I will work with this logic and we can hook it up to `checkpoint.rb`

**Comment by aomran** [comment]
I might change it up a bit to simplify it, so it might return `nil` instead of `false` but that shouldn't matter since nil is false if you're doing `if <return value>` instead of checking directly for falseness (`<return_value> == false`).

**Comment by aomran** [comment]
With a 75% as a threshold: 
- 2 students (fixtures for tests), the hasn't voted box never shows up
- 4 students (demo accounts), the box only shows up if 3/4 voted. 
- 8 students (Canvas demo accounts) the box shows up if 6 or 7 students out of the 8 voted.
- HackerYou's ~25 students, if 19-24 voted then it shows up. 

So this end ups being more of a "who's holding us up" thing now rather than explicitly "who hasn't voted".

It felt a bit weird with small numbers. I would have to create a bunch of fixtures (new classroom, tracks, students, ratings, checkpoints, etc.) just to be able to test it. On my computer I have a test classroom with 6 students and it just felt weird to only see the box when only 1 person hasn't voted.

To fix this I used "floor" on the result of num_students*0.75. This rounds down and makes things more reasonable for the smaller class sizes. With 2 students, 1/2 shows the box, with 6 students, 1-2 missing votes shows the box, etc.

**Comment by aomran** [comment]
This branch is ready to be reviewed and merged. Paula won't have time to do this so Nachi or Ali, please do a quick check and merge. 

Summary of changes:
- minor model and controllers refactors that don't change the end result, just make the code better.
- added some validations (50 char for expectation, 200 characters for success criteria, presence of score)
- fix issue#107, students can't join a class twice
- clearer flash message if a teacher tries to add the same classroom
- refactor of hasn't voted box

**Comment by aomran** [comment]
This last commit was made because I remembered that we left something half finished in the previous branch. Now on initial load of the page, if the browser max width is 480 then the side navigation will turn into a select tag.

**Comment by aomran** [comment]
Ok now done... I know that seems to mean nothing sometimes.

**Comment by nachiketkumar** [comment]
I will review and merge this in a bit- don't worry.

**Pull request merged**
