### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by aomran**
If you find small things that can be changed without too much effort then please post them here and lets address them when we can. 

Paula, myself and Ali discussed briefly yesterday that the bars should report % not count because even with a relatively small class (25 students), the counts get hard to reason about. Since this is all subjective data that is supposed to quickly give the teacher an idea (i.e. be actionable) the right thing to do would be to report percents. I made the percent round to nearest whole number (even if the bar width itself doesn't do that) because of two things:
1. The width needs to be precise so that the whole bar fills up.
2. The reported % doesn't need to be precise and would give the idea of "precise data" when we just want the teacher to "get a pulse".
## To Do
- [x] Show % count instead of actual numbers (on tracks index view analytics).
- [x] Position of the numbered label for requesters badge is off. (Was fixed in the previous merge into master)
- [x] Show progress bar counts on `:hover`
- [x] Fix scrollbar on large screens around 1470px mark.
- [x] Check polling speed
- [x] Check sign-in and sign-out events again.
- [x] Fix students being able to see move cursor and link title on individual checkpoints.
- [x] Add "Remember Me" checkbox to login form which stores session in permanent cookie.
- [x] Default order of checkpoints should be by ID and in ASC order when position is not available.
- [x] Requesters page is realtime even with multiple teachers using it.
- [x] When requesters number changes, the title of the page changes too
- [x] Change fixed nav min-height.
- [x] Add toggle for students to show/hide all success criteria

### CODE REVIEW

**Comment by aomran** [comment]
Nice new github design.

**Comment by nachiketkumar** [comment]
Yes, my first reaction was whoa things are different! It's a lot more subtle though-- it was easier to see quickly whether the build passed and was ready to merge or not, not with just the icon standing out it's a little harder. I like the other parts of the redesign though...

Agree about percentages. It's harder to see really small values on the bar, and I don't think that will change. For example, currently there are 19 'somewhat' understand responses for Explore CSS, out of a total possible responses for that track, which will be 5% when rounded. The text is going to overflow the bar, since the bar is accurate and not rounded up. If there was say 10 responses instead of 19, this would be even more exaggerated. Not sure what the solution could be?

**Comment by nachiketkumar** [comment]
One possible solution- since we only want to give a pulse, and teachers can easily go into analytics to get the details, we could not show any % or numbers, just the bars.

On hover, we could have tooltips that show the %. On mobile this wont be visible, but you would still get the pulse based purely on the bar sizes.

**Comment by Peak19** [comment]
I agree with Nachi's suggestion of using tooltips to give you percentage information. Most of the time it should be pretty clear to the teacher how people are answering. Percentage can be there to just reinforce the understanding if there's uncertainty. "Is that fully 25% of the class feels that way or just 5%? Oh, it's 15%. Cool."

**Comment by aomran** [comment]
Do you want to do tooltips through the `title` attribute or by putting a hidden element inside of each bar?

**Comment by nachiketkumar** [comment]
probably hidden element, since title is too slow to show up.

**Comment by aomran** [comment]
Does something like this work for you?

```
<div class="progress-bar progress-bar--"><span class="progress-bar-label"></span></div>
```

**Comment by nachiketkumar** [comment]
yup that should work. I can position the `<span>` absolutely and style it appropriately.

**Comment by aomran** [comment]
Ok that should do it, the percentage is now inside of `span.progress-bar-label`.

**Comment by aomran** [comment]
btw on bigger screens, there's now a scroll-bar inside the main content area. Something I think you fixed before. Just a heads up since we have huge screens here.

**Comment by nachiketkumar** [comment]
Can you explain more about the scroll bar- is it appearing throughout the app? a vertical or horizontal scroll-bar?

**Comment by aomran** [comment]
It appears when the content is scrollable vertically, so on track and analytics show pages. The bar appears around the 1470px width.

**Comment by nachiketkumar** [comment]
Ok I was able to replicate it....weird. I'll have to see why it's happening.

**Comment by aomran** [comment]
See updated to-do list above. Nothing on there is urgent.

**Comment by aomran** [comment]
Updated to do list above and removed the following two:
- Teachers should get a message encouraging checkpoint creation when track has 0 checkpoints.
- Students need to be notified of removal from class.

I think these are not minor changes so maybe we can work on them in a later branch.

**Comment by aomran** [comment]
The styling of the checkbox should probably be better (label + checkbox) together but that's a minor issue.

**Comment by aomran** [comment]
For the "Fix students being able to see move cursor and link title on individual checkpoints." issue -- do you have any idea why it's happening? The JavaScript should only run for teachers so is the drag/drop icon added using css?

**Comment by nachiketkumar** [comment]
Yes the drag-drop cursor was through css and the title was applied to the `.h5` unconditionally. This last commit should fix it.

**Comment by aomran** [comment]
I check polling speed - it seems fine. There are situations where it looks like the polling is happening faster but that's just because events end up happening in the middle of the 10 sec. poll.

**Comment by aomran** [comment]
The sign-in event works for me every time. The sign out event sometimes doesn't happen. Apparently this is a common problem when events are attached to clicks. This is because the event has to get tracked and sent to segmentio before sending the user to where they wanted to go -- somehow this sometimes doesn't happen

**Comment by nachiketkumar** [comment]
So the show `.progress-bar-label` on `:hover` is going to take a little work. The issue is the way the progress bar is currently structured doesn't allow for absolute positioning of that span. Have a look at the last commit.

I was trying to change the structure through the `analytics_helper.rb` file but I wasn't able to do so. You can uncomment my block and comment out yours to see.

Basically the structure that I think would work is this:

``` html
<div class="progress-bar">
  <div class="progress-bar-#{SCORE_WORD[counts[:score]]}" style="width: #{counts[:percent]}%">
</div>
  <div class="progress-bar-label"></div>
</div>
```

I'll have to rewrite some styles and play around with it...the same styles are currently being used in the analytics views as well so I have to make sure it doesn't affect that.

**Comment by aomran** [comment]
I can fix  the helper to match the snippet of code that you posted above.

**Comment by aomran** [comment]
Ok I changed the markup. You might need to change where the `style="width"` goes though.

**Comment by nachiketkumar** [comment]
Ok, that helped, but I seem to have another problem that I don't see an easy solution for.

I can't apply `overflow:hidden` to `.progress-bkgd`, otherwise it doesn't show the tooltips on hover. But if I don't apply it, I can't clip the progress containers to the curved radius of the parent.

Have a look- thoughts?

**Comment by aomran** [comment]
One suggestion is to use the jQuery UI tooltip library. It takes the "title" attribute and makes into a nice tooltip that can be styled pretty much however you like. This removes the need for extra markup.

Have a look: https://jqueryui.com/tooltip/

We already use jQuery UI so it's just a matter of loading the component and activating it.

**Comment by nachiketkumar** [comment]
Will give that a try after lunch, thanks.

**Comment by aomran** [comment]
I wrote a rake task for fixing the position of existing checkpoints, just run `$ rake curri:checkpoint_positions`

**Comment by nachiketkumar** [comment]
While this branch is still up- did we want % counts on the analytics page as well? The checklist says only for tracks index page but currently it is on analytics page too. It's hidden due to the way I've positioned the containing div but I can fix that.

**Comment by aomran** [comment]
We should be consistent with how the bars look so yeah hover on analytics too.

**Pull request merged**
