### PR TITLE
start to change page titles

### PR DESCRIPTION
**Pull request by nachiketkumar**
Better page titles:
- Is this the best way to do it? I took the logic from Hartls tutorial.
- How do I set up the code for views where the title is more dynamic, like a particular class? I tried doing that in tracks>show, but it didn't work.

EDIT: nm, I was looking at the show view when I should have been looking at the tracks>index view. It works.

### CODE REVIEW

**Comment by aomran** [comment]
Yeah this seems like a reasonable way to do it.

**Comment by nachiketkumar** [comment]
Ready to merge. I got most of them I think, except for the classroom>edit view. I am not sure if this will be a page in itself or if there is an easier way to allow editing the title of the classroom, which is all this view is doing.

**Comment by nachiketkumar** [comment]
Error in test, best I can tell due to this line in tracks>`edit.html.erb`

``` irb
<% provide(:title, 'Edit '+@track.name) %>
```

**Comment by aomran** [comment]
If a user puts nothing for the track name then the `@track` object in memory gets a name of null. The track doesn't update the database but redirects to the edit page and says "can't leave name blank... etc." but for that moment at least in memory the name is blank. Concatenation of nulls doesn't work. To avoid these issues always use Ruby's string Interpolation instead of the regular concatenation with plus signs. So prefer `"Edit #{@track.name}"` to `'Edit' + @track.name`.

**Comment by nachiketkumar** [comment]
I could have sworn that I saw the last commit had passed on semaphore but now that I've merged this PR, it says pending. And the last commit was 3 hours ago! I'm confused.

EDIT: Weird- now its green. Must have been a github bug.

**Pull request merged**
