### PR TITLE
create logo, add to layout login, animate svg

### PR DESCRIPTION
**Pull request by nachiketkumar**
Have a look, I'm using an inline SVG for the logo on the login screens, so that I can animate using CSS. [Not supported](http://caniuse.com/#search=svg) in IE8 and below and older ios safari and android, but I'm not too worried for now. We can use fallbacks when warranted.

### CODE REVIEW

**Comment by aomran** [comment]
Thats looks cool - really like it.

**Comment by pjfranzini** [comment]
Great idea the 3-step animation

**Comment by nachiketkumar** [comment]
Ready to merge. 

Animation doesnt work on mobile, if you can think of an easy fix, go ahead, if not, merge.

**Comment by aomran** [comment]
Do you want to add the logo to the app itself in this branch or do that later?

**Comment by nachiketkumar** [comment]
I'll do that later, it's going to be a little different for when the nav is open or not, and I'll use the existing .svg sprite file for that. I made a small change- a more specific class name to avoid confusion.

**Comment by aomran** [comment]
Ok I will merge this then when the tests pass.

**Comment by aomran** [comment]
I think the CheckpointTest#test_hasnt_voted_list_for_class_with_two_students test is flaky. It passes sometimes and fails sometimes. Something weird is going on with the test. My best guess is that the order of the tests matters for this test, so the test needs to be fixed.

**Comment by aomran** [comment]
Also a feature test failed because it couldn't find a button.

**Comment by aomran** [comment]
I've simplified the test - lets see if that helps. I'll merge once the build passes.

**Pull request merged**
