### PR TITLE
set up login layout

### PR DESCRIPTION
**Pull request by nachiketkumar**
This branch is for the separate styling of the login page. As is common for most apps, the login page is styled somewhat differently from the app:
- no app navigation
- minimal other navigation
- minimal distraction from the desired action --> log in.

Let's keep this branch open till I'm done with styling it. It could probably use a test to ensure that the login page uses the `login_layout.html.erb`.

### CODE REVIEW

**Comment by nachiketkumar** [comment]
Some help needed:
- Why is the button so weirdly styled?
- If you enter an incorrect login or try to login without credentials, the resulting view uses the `application.html.erb` instead of the `login_layout.html.erb` even though in the controller it seems to be set up to `render :new` if user is not authenticated.

**Comment by aomran** [comment]
Try `render :new, layout: "login_layout"` in the create action.

**Comment by aomran** [comment]
Also the button is messed up because the `btn` and `btn-primary` classes are on the div that wraps the input instead of directly on the input.

**Comment by nachiketkumar** [comment]
Thanks Ahmed. I realized why the button was messed up when I was out at dinner last night, then saw your note. It's hard to stop thinking about this stuff!

**Comment by aomran** [comment]
Yeah the JavaScript does the adding of `.nav-open`

**Comment by aomran** [comment]
I think these extra merges can be avoided somehow, I'll have to look into it. Anyway the `.nav-open.` issue should be resolved.

**Comment by nachiketkumar** [comment]
I don't understand the issue about the extra merges- should I not be working on parts in branches like this? Or did you mean something else?

**Comment by aomran** [comment]
I was talking about the extra commit that git forced me into. The `Merge branch 'login' of github.com:aomra015/curri into login`... which frankly wasn't necessary. We've seen this happen before. No idea why it does it.

**Comment by nachiketkumar** [comment]
Remaining on this branch:
- Add final logo and wordmark when it is ready in place of the **Log In** text
- Apply this template to the pswd reset view, registration view and student registration view as well.
- Remove uservoice widget from this page?

**Comment by aomran** [comment]
By the way, when the user is not logged in the register link isn't showing up anymore. I guess the `logged_out_nav` partial isn't needed anymore unless you want to move it to the `login_layout` template.

**Comment by nachiketkumar** [comment]
I'll add a register link below login button. No need for a separate nav, correct?

**Comment by aomran** [comment]
That works for me.

**Comment by aomran** [comment]
By the way I can take care of the uservoice widget in the mixpanel branch that I opened up. What I want to do is only enable the widget if the user is logged on and also use the widget's `identify` feature, which like mixpanel allows us to know who is sending us feedback/comments/requests etc.

**Comment by nachiketkumar** [comment]
Sounds good- just to be clear for myself, you are doing it in the mixpanel branch for convenience, and not because uservoice and mixpanel are somehow connected, correct?

**Comment by aomran** [comment]
Pretty much.

**Comment by nachiketkumar** [comment]
I keep thinking I'm almost done but there are still a few things:
- Have a look at what I have so far and let me know of any issues. I've done login, register as teacher, and pswd reset.
- How do I access the view a student would see from an invitation link? Do I need to send a mock invitation and use that URL? I've styled the code in the `new.html.erb` in Students (views) but I just want to confirm it looks OK.
- I want to style the error messages and their position. Right now it's all over the place.

EDIT: That's what I did to get to the students>new view.
- Do we need `id`s with various submit buttons? I've been deleting them as I am not relying on them for styling.

**Comment by aomran** [comment]
The ids might be used in the tests. If a feature test fails then you deleted one that is being used there. I know that the log-in and log-out links have ids for that.

**Comment by aomran** [comment]
The forms look really good. I checked them all.

**Comment by aomran** [comment]
Everything up to this point has been reviewed and looks good. If you want it merged then just say so. Also I find that these extra merge commits seem to happen when we do `$ git pull` without specifying the remote branch. So lets try always being explicit, i.e. `$ git pull origin <branch-name>`.

**Comment by nachiketkumar** [comment]
I don't think that's it- for me the extra merges have happened when I tried to push to this branch and failed because you had a commit that I hadn't pulled. I haven't set up to track this branch, so I can't do a `git pull`, I have to be explicit and specify the remote branch. I then get prompted to add a message to the merge which I skip out of.

Let's go ahead and merge this one then, I will fix the flash warnings when I style them in the app. We also need to get rid of the bootstrap JS library or at least only load the part we need, but probably not a priority for the pilot.

**Comment by pjfranzini** [comment]
I had Ahmed give me a quick look, looks good. We were wondering why the password reset button is red with a blue edge, wondering if that is intentional (he thinks it looks bugged, I think it looks kind of cool but agree that it might not be what you meant).

**Comment by nachiketkumar** [comment]
Good catch. It's loading an old style since I added the ID back in. Let me fix it then merge it.

**Pull request merged**
