### PR TITLE
Ajaxify

### PR DESCRIPTION
**Pull request by aomran**
As I get time, I will be working on this branch to "AJAXify" the app. Here is the plan:
### Immediate page update (DONE)
- Destroying a checkpoint
- Destroying an invitation, i.e. removing student from class
- Removing students from help queue
- Toggling help status - for students
### Sorting (DONE)

Classrooms order doesn't matter (IMO). It's a small list so default sorting might be enough. Tracks should be ordered in a sensible way. If order matters then the teacher should input a start date. We can sort by date and fallback to ordering by id when no date is picked.

Checkpoints can be ordered using a drag/drop sort mechanism.

### CODE REVIEW

**Comment by aomran** [comment]
"Toggling help status" for students currently gives two notices. "Your teacher was notified that you need help." and "You were removed from the help queue.". Do you guys think that these notices are necessary? The "removed from queue" is obvious since the button changes. The "your teacher was notified" is a good message for a first time user but can get repetitive once you're used to what the button does.

**Comment by nachiketkumar** [comment]
I agree that this message can get repetitive. I've used apps where prompts can be permanently disabled, something to the effect of 'OK I get it, don't show me this again"

How easy is something like this to implement? That way we leave it to the user.

**Comment by aomran** [comment]
That would involve storing the user's option/choice in the database. So it's not too difficulty, just overkill in most situations. 

This issue might be resolved with some good tooltips. The default browser tooltips are bad because they take too long to show up - I mean something like the "Tracks" and "Classrooms" tooltips that show up immediately when the nav is collapsed. 

There is space under the buttons for this tooltip. It can say "Notify your teacher" for the "Ask for help" button and "Leave help queue" for the "In help queue" button. Then we get rid of the notifications and the UI becomes easier to understand because before the user even performs the action, they get the information explaining the feature.

**Comment by nachiketkumar** [comment]
Good points. I'll work on this when I'm done with the remaining restyling- mainly the analytics view I think.

The only issue is because it's on hover, it doesnt work for mobile. But we can show the alert only on mobile sizes and make it auto disappear in a few seconds.

**Comment by aomran** [comment]
The help status toggle now works but there are no tooltips or notifications when JS is enabled. One solution that might work well for both desktop and mobile is a tooltip that gets activated not on hover but on click. Here's how I imagine it working:
- The tooltip markup is always there but with no content and is hidden.
- When user clicks on the button, the message is injected into the tooltip div/span and it is shown.
- After a second or two, the tooltip gets hidden automatically.

**Comment by nachiketkumar** [comment]
Yup that makes sense too. It will be a tooltip similar to what students see when they are rating checkpoints- hidden till click, except it is not interactable and gets hidden automatically.

**Comment by aomran** [comment]
UI issue with sorting: If you test this out you'll notice that if you scroll down and try to drag a checkpoint, the checkpoint will drag but you won't see the element... seems like there is an offset issue... the checkpoint stays at the top of the page while being dragged. Did some research, people suggest it's an overflow issue or something of that sort. Don't have time to debug this at the moment.

**Comment by nachiketkumar** [comment]
How are you being able to drag the checkpoint? I can't tell where to click to drag it- all I end up doing is selecting the text!

**Comment by aomran** [comment]
The `handle: '.expectation'` lets you decide which element is the "handle". So that would be the expectation for the checkpoint. Although of course you can have a "drag/drop" icon beside the edit and delete icons for doing this.

**Comment by aomran** [comment]
My last commit broke it. Let me fix this.

**Comment by nachiketkumar** [comment]
Seems to work pretty well for me!

If you drag the last checkpoint up- and go over the fixed header, the page scrolls, and you are able to drop it in place of the first one. 

Issues 
- there is no indicator that it is sortable- the move cursor shows up only after you click on the checkpoint. The solution, as you said is to add an icon which would have the move cursor applied to it. I can work on that.
- the new order is not saved, but I don't think you were trying to achieve that yet.
- I would also like some sort of blank dash-bordered div show up instead of the completely empty space, to show that the area is droppable-into, if that makes sense. I'll need to figure out how to style that....no clue at all right now. EDIT: probably this? http://jqueryui.com/sortable/#placeholder

**Comment by aomran** [comment]
Yeah placeholder is a class that makes this easy to do. And yep will work on server-side next. 

I think I didn't explain the issue well. Scroll down and try to drag one of the items below. Now compare that with the items above the fold. You'll see that the items under the fold (i.e. require you scrolling) will drag/drop but you don't see the element when it is being dragged. The element is for some reason above the fold.

**Comment by nachiketkumar** [comment]
I guess I still don't understand. I see the element as I'm scrolling both dragging from top to bottom and the other way around. I made a [quick screencast](https://www.dropbox.com/s/ttr1v137x762vjq/sorting%20checkpoints.mov) of it- if you have quicktime you can make one and show me what you're seeing.

**Comment by aomran** [comment]
Have a look at this: https://dl.dropboxusercontent.com/u/52112273/checkpoint-sort.mov (when it finishes uploading...).

**Comment by nachiketkumar** [comment]
Weird- I see what you were saying but I can't replicate it. I've tried it on FF, Safari and Chrome and I never lose the element as you seem to be doing...Is it happening on Paula's computer? Ali, if you could weigh in and let us know as well?

**Comment by aomran** [comment]
Looks like the bug happens when the side navigation is open. In my screencast it's open, in yours it's collapsed. I collapsed/opened and verified the issue.

**Comment by nachiketkumar** [comment]
Yup, I see the problem now. It is an overflow issue- you're right. I'll need to fix a couple of rules and hopefully that should fix it.

**Comment by nachiketkumar** [comment]
Besides the adding/editing resources, this branch is almost done- the only other thing is styling the placeholder for the drag/drop- see my commit note. Once that is fixed, can we merge this and handle the add/edit resources on a separate branch, even though it has to do with AJAX?

**Comment by aomran** [comment]
Bottom-border solution is fine with me. Also looks like the placeholder class wasn't working because the placeholder height was something like 10px. So i wrote some JS to set the height equal to the item being dragged (which should be default...).

**Comment by nachiketkumar** [comment]
Great- final part is I want to add little draggable markers for each checkpoint. Once that is done this should be ready to merge from my end...

**Comment by aomran** [comment]
This all looks great. Merge whenever you like. I took the add/edit notes and moved them into an issue that can be tackled on a new branch.

**Comment by nachiketkumar** [comment]
This should take care of what was remaining on this branch- let me know if it makes sense. I added some cursors and titles to make it a little clearer. 

JqueryUI doesn't quite work on touch screens (at least some actions like drag/drop). If we want to offer this on mobile, then we would need something else...maybe something like [this](https://github.com/furf/jquery-ui-touch-punch) or a better solution. I didn't look too long for this.

I'll merge in about 30 minutes to give you time to review and allow tests to pass.

**Pull request merged**
