### PR TITLE
minor style fixes

### PR DESCRIPTION
**Pull request by nachiketkumar**
A few small things that were bothering me, add to this if there's something minor you'd like changed regarding styles:
- changed so that main content area is not scrollable in certain situations (when subnav is open and when main nav is shown at mobile sizes)
- slight change in the subnav- the 'account' title in the subnav has been replaced by a small arrow showing the subnav belongs to account.
- reworded title of the expand/collapse link.
##### Issues:
- The account link when clicked to open the subnav always takes you to the top of the page. Not a big deal but would be nice if it didn't do that- I'm not sure why that is.
- The same link when clicked to open the subnav and then clicked again to close it, results in the `.pull-right` div in the header to be momentarily out of place, off to the left a bit. This resolves itself if you scroll/resize the window/refresh. Again not a big deal.

If either of you can figure out one or both of the solutions in less than 15-20 minutes, great, if not, this can be merged.

### CODE REVIEW

**Comment by aomran** [comment]
Weird behaviour, no idea why it's doing that.

**Comment by aomran** [comment]
Also the fixed header overlaps with some content when you scroll down (especially buttons).

**Comment by nachiketkumar** [comment]
Yup- I made a note of that behaviour (overlapping buttons) in the pageheader branch; I think it's to do with some old styles that will be removed. I know that if the opacity of any object is <1, it somehow changes the stacking order. So I changed all the opacity of the progress bars to 1, they were also overlapping. I am pretty sure this issue will get resolved when I move on to styling the main content with the new layout structure.

**Comment by nachiketkumar** [comment]
Similarly, when on mobile view, if you are scrolled down and then click the menu to open the nav, you automatically get scrolled back to the top of the page.

**Comment by nachiketkumar** [comment]
Shall I merge this or is anyone trying to figure out the small bugs mentioned?

**Comment by aomran** [comment]
I think the small bugs should go on pivotal tracker and we'll get to them when time permits.

**Pull request merged**
