### PR TITLE
Multiple teachers

### PR DESCRIPTION
**Pull request by aomran**
To work with this branch you will need to reset your database because the relationship between teachers and classrooms changes. So:

```
$ rake db:drop
$ rake db:setup
```

How this feature works:
1. When a classroom is created, a unique 8 character long string is created called `teacher_token`.
2. Clicking "add classroom" will give you the option of joining a classroom instead by inputing the token.
3. Invalid token will redirect back to the form and say "Invalid Token" **Issue 1**
4. Valid token will add the teacher with full admin rights.
5. On a classroom's edit page (by clicking "mange classroom") you will see the statement: `To invite additional teachers to the classroom please use the following token p8vHvP_4`. The teacher then passes this token to their colleagues to get them to join.

Issues:
1. The flash notifications are not displayed on the page. The markup is there, the style just needs to be fixed.

### CODE REVIEW

**Comment by nachiketkumar** [comment]
Yup I need to style the flash notifications. Some questions:
- Is there an 'super-admin' teacher with superpowers?
- Can other teachers once invited be removed (for whatever reason)?

Likely not an issue for the pilot, but could be an issue down the road.

**Comment by pjfranzini** [comment]
no and no, at least atm

**Comment by pjfranzini** [comment]
Ahmed and I are discussing a system where "Delete Classroom" is replaced by "Leave Classroom", so that co-teachers can't accidentally delete a classroom. I pointed out that what about test classrooms (something you might make to learn the system), you'd want to be able to eventually git rid of them. So we agreed that a good compromise might be that you can only delete a classroom if you are the sole teacher and there are no students in it. So to delete a classroom, you'd have to have no students, or kick them all, then agree with your co-teachers (should you have any) that you are deleting it, everyone one but one would leave, and the last one out deletes the classroom. Comments/ideas ?

**Comment by nachiketkumar** [comment]
I quickly created a google docs [spreadsheet](https://docs.google.com/a/nachiketkumar.com/spreadsheet/ccc?key=0AvBly_Puza4XdFVQUmgtMWhET2FNNU5fcFQ2c2I0NHc&usp=sharing) showing how I envision this.

Before looking at it, how you have it now will probably work for the pilot, and we dont need to worry about people struggling to delete test classrooms.

I'm thinking of a system where a classroom has an superadmin owner/teacher, who can invite students as well as other 'collaborators', who have reduced admin privileges.

Not sure how much of a spanner this throws into the works, but if implemented, it would be a more elegant experience.

**Comment by pjfranzini** [comment]
made a number of text amendments to hopefully make things clearer to users
made one of the sample tracks published by default and the other one unpublished
made the track index view display which tracks are unpublished

**Comment by aomran** [comment]
This branch should be ready to merge. Although once that's done I'll have to reset the postgres database on Heroku.

**Pull request merged**
