### PR TITLE
rename some classes to be more modular, start styling tracks index

### PR DESCRIPTION
**Pull request by nachiketkumar**
The tracks index will be styled similar to the classroom index:
- Paula, you can remove the flash notice for login here if you'd like.

### CODE REVIEW

**Comment by nachiketkumar** [comment]
I'm struggling a bit with formatting the start/end times here. I tried through the helper and to call it in the `_track.html.erb` but it didn't work. It's still in the helper, commented out.

I keep getting an error, if I can get it to show up I can format it appropriately, I want it to say "Track start: 2 PM Jan 18, 2014" and so on for stop time. 

If there are no start/stop times assigned, this is a good spot to call out that issue as well, just as I am calling out unpublished tracks and invitations in the classroom index.

I'd like help with that too, so if no track start/end time, then I want some messaging to show (same icons, text will say something like "no start time defined")

**Comment by aomran** [comment]
The errors probably appear when a track doesn't have the start/end times. Check with `track.phasing?` and then call the helper, `else` show a message.

**Comment by nachiketkumar** [comment]
I need some help with the teacher view for the analytics. We talked about this on basecamp [here](https://basecamp.com/2358567/projects/3582681-curri/messages/18382151-ui-ux-wireframes#comment_111450327), and that's exactly what I want to implement. I already have the `<% else %>` block in place, it just needs a partial :)

**Comment by aomran** [comment]
This is good to go once tests pass.

**Pull request merged**
