### PR TITLE
enabled mixpanel tracking

### PR DESCRIPTION
**Pull request by aomran**
I have implemented the code that should theoretically work but this needs to be tested by hand thoroughly before it is merged. There's a lot here so here is the explanation:
- The mixpanel JavaScript library is inside a partial so that it doesn't clutter the layout. I included it with `<%= render 'shared/mixpanel_js' %>`. If an environment variable is set (i.e. when in production) then we use the production project. This separates our data in Mixpanel based on the environment we're in.
- The `<%= js_render_user(current_user) if current_user %>` line takes the current user's information and make it available in the JavaScript.
- In `domready.js.coffee` line 48 I identify the user, register super properties and set their information in Mixpanel's people feature. This only happens if the user is logged in.
## Tracking click events

Some events can be tracked by seeing which links are clicked. 
- Rate checkpoint: After the AJAX request is successful (line 14) `mixpanel.track("Rate checkpoint", { score: data.current_score, checkpoint_id: data.checkpoint_id })`
- Sign out: `mixpanel.track_links("#logout-link", "Sign out")`

These event handlers go in the domready.js.coffee file. 
## Tracking other evens

Some events are not simple enough to be tracked by just looking at a "click". What if they click on the sign up form and it failed? What if they click the sign in form and their password was wrong? These kinds of events need to be tracked on "success". So what I did was added a custom "flash" for these events in the appropriate controller.
- View analytics: Analytics controller - show action, `flash.now[:track] = { event_name: "View analytics page", properties: {classroom_id: @classroom.id, track_id: @track.id } }`
- Views track: Tracks controller - show action, `flash.now[:track] = { event_name: "Student views track page", properties: {classroom_id: @classroom.id, track_id: @track.id } }`
- Sign in: Sessions controller - create action, `flash[:track] = { event_name: "User Sign In" }`
- Sign up: Students controller - create & enroll actions, Teachers controller - create action, `flash[:track] = { event_name: "User Sign Up" } or flash[:track] = { event_name: "User joins classroom" }`
- Create checkpoint: Checkpoints controller - create action, `flash[:track] = { event_name: "Create checkpoint", properties: { classroom_id: @classroom.id, track_id: @track.id, checkpoint_id: @checkpoint.id } }`

Then in the application.html.erb view:

``` erb
<% if flash[:track] %>
    <%= mixpanel_track(flash[:track][:event_name], flash[:track][:properties]) %>
<% end %>
```

The `mixpanel_track` method is a helper method which writes a bit of JavaScript to the page so that the event gets fired off and stored/tracked by Mixpanel.

### CODE REVIEW

**Comment by pjfranzini** [comment]
Looks good. I have tried out each of the events and their associated properties (eg see the events sorted by browser, First Name, etc etc) and everything seems to work fine. The Rate Checkpoint event was missing the properties of classroom and track ids so I added these. We did a data reset (only Ahmed, the account owner, can do this operation) to clean up issues caused by having changed property names for email etc. We should add some of the other events we discussed, but that doesn't necessarily have to be done in this branch/before merging this branch. I will certainly be looking at this more in the next day or two though so we could wait on that before merging if desired.

**Comment by nachiketkumar** [comment]
Sounds good. I haven't spent much time seeing how this works, but I would like to once the front end is in a good state. Ahmed, I think your first post on this pull request would make a good entry in the wiki- could you transfer it?

**Comment by aomran** [comment]
I also moved the first post into a wiki page.

**Comment by aomran** [comment]
I signed us up for KeenIO and switched the code to use segmentIO. This change will need to be tested.

**Comment by aomran** [comment]
If the tracking is working correctly then this is ready to be merged.

**Comment by nachiketkumar** [comment]
Happy to merge this but since Paula's been involved in testing the code in this branch, I'd rather leave it to her :)

**Comment by pjfranzini** [comment]
So I did a bunch of testing, found some issues that Ahmed and I fixed. I have confirmed that each kind of event is getting through (for the most part at least), and with the appropriate data attached. There is a noticeable flakiness associated with the combination of logging out (not the most interesting of events anyhow) and KeenIO. Mixpanel has missed a couple (out of 60) of these events, but much much fewer. KeenIO has also, very occasionally, missed a couple events of other types. SegmentIO and Mixpanel both seem to be catching pretty much everything. It's good that we got both up for the pilot and will be able to compare things. I will go ahead and merge this now; we can add the other events soon separately, and I still need to look into funnels and so on.

**Comment by nachiketkumar** [comment]
Sounds good. I'm sure you got the email from segment.io about webinars? It might be worth sitting in on one of those if you have the time and want any questions answered.

**Pull request merged**
