### PR TITLE
Navigation ui

### PR DESCRIPTION
**Pull request by nachiketkumar**
I've got the basic new nav structure in place:
- At the very top of the nav menu, before the Classrooms link, will be our logo, which could link to the landing page. What do you think about that? Mailchimp and treehouse both link to their dashboards, whereas basecamps links to the projects page- so our equivalent could be our logo linking to the classrooms page, which is the 'home' page.
- I need to still figure out the best way to show the secondary nav (requesters for teachers, help toggle for students) which will appear in the main app area, top right.
- The account menu (name, user type, edit account and log out) needs to be worked on- as per our discussion on invision, this will be a hover menu. Also need to think about how that hover menu would translate for smaller screens. 
- I need some help with JS. On clicking the expand arrow on the bottom of the main nav, I need the class `.nav-open` to be applied to the body. This class should be removed when either the arrow or any of the nav links is clicked. This same action will be repeated when the mobile nav burger icon is clicked, but I should be able to do that  on seeing how you set this up.

### CODE REVIEW

**Comment by nachiketkumar** [comment]
Build failed on Semaphore- I changed the 'Profile' to 'Account' and I think that's what caused it.

**Comment by aomran** [comment]
- I think the logo should link to `root_path`. Right now that's the classrooms index. It makes sense to keep people in the app.
- After taking a look at the branch I'll help with the js stuff.
- I really like the icons for classrooms/tracks/analytics but we should have the words there as a hover/tooltip. This helps people learn which icon is which.

**Comment by aomran** [comment]
The js is added. JavaScript is not persisted so when the page refreshes, everything goes back to the default. This means the navigation doesn't have to be collapsed when someone clicks on any of the links, it will do it automatically. Of course we can persist the user's choice by storing it in the session if that's what you want to do. We have both options available to us.

**Comment by aomran** [comment]
I'll fix the tests next.

**Comment by pjfranzini** [comment]
I agree that the logo should link to root_path -- our app's "home page" -- not landing page.

I agree that the icons are very nice, but somewhat confusing as an unlabeled default. I like the words as hover/tooltip idea. I would tend to go for menus uncollapsed as default as well.

**Comment by pjfranzini** [comment]
"Of course we can persist the user's choice by storing it in the session " -- I would think we would have to. No matter what is the default, if the user chooses the other way, they don't want to have to redo that each time they change page.

**Comment by nachiketkumar** [comment]
Thanks for all the input.
- I'll work on integrating nav hover for the names.
- Logo will link to root_path
- I think we could go either way with persisting user choice or not, mainly because our navigation is very simple. As it is, when you first start, there's only 1 nav option, and a few more become available as you go deeper in the app. Add to that, the expand/collapse option is there. If it is easy to persist it in the session, then lets go for it.

**Comment by aomran** [comment]
When the minitest branch gets merged into master I'll merge it into here, fix the tests and take a look at the `.selected` class that you need.

**Comment by aomran** [comment]
I think the expanded version makes sense as a default except for smaller devices although it's not a big deal. We can tweak these things later. I made it default using JavaScript. If that's not ok then I can remove it.

Also I created a helper called `link_to_selected` which delegates to `link_to` except it handles adding the `.selected` class for you with the right path.

**Comment by aomran** [comment]
Yeah localStorage persists for a long time unless the user deletes it or the browser cleans it up. Anyway the latest version of the JavaScript has one place where we can set the default (collapse/expand). Line 5 of https://github.com/aomra015/curri/blob/8a703703b6557218a261a6c398a41c22b1572dcb/app/assets/javascripts/ui_options.js.coffee just change true to false and the default becomes the collapsed navigation. We can even later check for devices and set it based on that.

**Comment by aomran** [comment]
This is good to go. Anyone else can safely merge and delete the branch.

**Comment by pjfranzini** [comment]
Looks good to me!

**Pull request merged**
