### PR TITLE
add description to classroom

### PR DESCRIPTION
**Pull request by aomran**
Re-opening the branch for one commit. The description for the classroom has been added. Note that if no description exists for a classroom then you won't see anything, go to the edit page to add one.

### CODE REVIEW

**Comment by nachiketkumar** [comment]
Nice. What's the process if I've already deleted this branch on my computer? Do I just add it as if it were a new branch?

Is the character count limited?

**Comment by aomran** [comment]
No validations but thats easy to add. Assume the branch is new.

**Comment by pjfranzini** [comment]
As well as adding the validation, I found some issues when cleaning up the usage of count versus size. Using size ended up getting a wrong value sometimes because of counter cache lives in the invitations model (i.e. classroom.students.count gives the number of students that have actually accepted an invitation while classroom.students.size gives the number of students invited). Since size is the more "correct" usage here, I set up an accepted scope to make sure the counts are correct. I also found inconsistencies in the variable used for the number itself and the pluralize method, so set up variables for all of these.

**Comment by aomran** [comment]
If there is nothing else to be done here then please merge.

**Comment by pjfranzini** [comment]
looks good

**Pull request merged**
