### PR TITLE
style track start end times

### PR DESCRIPTION
**Pull request by nachiketkumar**
Styling the tracks show view here. Besides the analytics view, this is the main section left to style.

Smaller parts remaining are all forms, add students view and requesters view.

### CODE REVIEW

**Comment by aomran** [comment]
The method is being used in the analytics show page too. Just a matter of switching that one too.

**Comment by aomran** [comment]
This should fix it.

**Comment by aomran** [comment]
Ok the test fails because you removed the marker. When you have the new UI for the students I'll fix this test.

**Comment by nachiketkumar** [comment]
I'm done with this branch for now and once the ratings have been hooked up it should be ready to merge.
- The UI is in place- clicking the caret show the ratings options to the left. These need to be hooked up to the actual ratings (previously `button_to` and still in the `checkpoints/_checkpoint.html.erb` file commented out).
- When rating option is clicked, the rating needs to be submitted and the caret needs to be replaced with the chosen rating face.
- When the rating is clicked again to change it, the same 3 options should show (or maybe only the other 2?), and if it is changed, then the new choice needs to remain in place.
- Clicking any of the ratings should also remove the `.show` class
- If it is easier to use svg images for this, I can certainly do that. 
- Unrelated, but students are seeing unpublished tracks in the sidebar navigation on this page.

**Comment by aomran** [comment]
At this point the branch should be in a good state. I've fixed the tests and resolved merge conflicts with master.

**Comment by nachiketkumar** [comment]
I'll finish this up once I've fixed the hover styles, and/or switched to svg, and then merge. I might break some tests while you're gone but hopefully not.

**Pull request merged**
