### PR TITLE
Classrooms ui

### PR DESCRIPTION
**Pull request by nachiketkumar**
Starting to style the inside of the app, beginning with classrooms. Some other minor style issues along the way as well.

### CODE REVIEW

**Comment by aomran** [comment]
There is a google doc for the classroom fields: https://docs.google.com/document/d/1LbfuOxDBL5GDkMrj7YXRlxMKiP5JvihR-nltangzWt8/edit

Add a description is fine with me.

**Comment by nachiketkumar** [comment]
Cool. In case I didn't make it clear, I'd like your/Paula's help on fixing the line comments on this PR :).

**Comment by nachiketkumar** [comment]
As you can see, I'm beginning to play with adding an accent color. Paula, I think you might like to help decide what this could be. 

Some icons can be in this accent color, as well as the subtitle on each page. It also has to be something that doesn't clash with our color palette and is not overpowering yet bright enough- thoughts?

**Comment by pjfranzini** [comment]
going to look at it now, back to you soon

**Comment by pjfranzini** [comment]
It's not bad as is. Here's another suggestion to play with -- reddish browns are nice with slate blues, and specifically since main is 415463, which is hue 206, I'd try complementary, so hue 26; for example with S 100, B 72 that would give you b85000; or play around with S and B as you prefer. Going to look at your coding question(s) now.

**Comment by pjfranzini** [comment]
Here's the conditional stuff for the invitations pending and tracks unpublished :)

By the way, I'm not sure about that orange text, in combination with the $color-main: #415463 + the $color-accent: #A5A532. Maybe if the accent goes rust, the orange will clash less. Or maybe if you keep the accent color as is, another subtitle text (rust again? something more neutral?) would be better, it seems a little jarring as is.

**Comment by nachiketkumar** [comment]
Great! Thanks. This is ready to be merged. I'll keep working on the color issue- I wanted to keep it orange due to the symbolic nature- pending invitations and unpublished tracks _should_ be a warning, no?

EDIT: Actually, the number of tracks published currently includes all tracks,`<%= classroom.tracks.size %>` = published and unpublished, correct? I have a sample classroom locally that has only 1 unpublished track, but on the classrooms index it says 1 track published and 1 track unpublished.

**Comment by pjfranzini** [comment]
ah, k, I didnt look at the number on the tracks published, sorry.

for the description field, Ahmed said he could take a look somewhat later

Edit: and yes, your commit for the Tracks published count looks good to me

**Comment by nachiketkumar** [comment]
The addition of the textarea/classroom.description is not really a UI issue, so I've merged this. I'll be relying on pivotal and github a lot over the next 3 days to add tasks that I'd like you guys' help with, so make sure to check on there. I'm signed on to hipchat as well, so I'll check to see if anyone else is on there.

**Pull request merged**
