### PR TITLE
add teacher help toggle

### PR DESCRIPTION
**Pull request by nachiketkumar**
I want to set up the help toggle/requesters feature for students and teachers in this branch:
- I've already set up the requesters feature for teachers. A small badge gets added if there are requesters and the color of the icon changes to our primary blue color. If there are no requesters, it's a grey icon/no badge. Have a look. 
- Also, please look at my code for this in `._help_toggle.html.erb` and let me know if there's a better way to write it (the conditional code).
- Next step is to code the student help toggle.
##### Issues:
- When you are on the Requesters page, the classroom icon doesn't get the `.selected` class. Since requesters always belong to a particular classroom, this should be highlighted.
- The similarity of the teacher requesters icon and the uservoice icon is bothering me. Would it be OK/make sense to somehow move this under Account > Support (new link)?
- Does it make sense for this `.page-header` div to be fixed to the top of the browser window? More so for the students than the teachers, if they are further down on a page and want to click the help toggle, I wouldn't want to force them to scroll up. Similarly, if a teacher is further down on a page, and the # of requesters goes up, I would want that to always be in view. What do you think?

### CODE REVIEW

**Comment by aomran** [comment]
The pusher branch is really important to get through before I contribute here since I've made some changes there that will conflict slightly with this. When I'm done with pusher, we'll merge it and then I'll fix the merge conflicts with this one.

**Comment by nachiketkumar** [comment]
I'm working on the help toggle for students, and [this](http://codepen.io/nachiketkumar/pen/oivbr) is what I have so far.
- Can we make the functionality work through a checkbox? Semantically, a checkbox makes the most sense, a student is selecting whether or not they need help. Styling the checkbox this way (help from Lea Verou's [post](http://lea.verou.me/2013/03/ios-6-switch-style-checkboxes-with-pure-css/)) looks nice and gives visual feedback to the user that you have changed your answer.
- If yes, then I can go ahead and add the code for this in and get your help with hooking it up.
- 2 separate links (as we have it now) doesn't seem to me to be the best solution for what is essentially a checkbox.

Ahmed- I saw that after I had pushed this branch- the changes you have made, at least the ones I noticed on `_help_toggle.html.erb` will conflict, so go ahead and get that one done first.

**Comment by aomran** [comment]
I think the biggest issue will be making a checkbox submit a form as soon as it's checked/unchecked. We also need to keep in mind that people don't know there's a help queue unless we can explain it well. How do we get across what the help queue means? The word "off" doesn't really mean much to me, will it mean anything to the students? "Help" could mean many things.

We need to get across that clicking on this checkbox/button/link will put people in a queue so that they can get their question answered by the teacher. The latest terminology that I added to the other branch says "Not in queue" by default and then clicking the button says "in queue". 

So in my opinion we need to give the same feel that you get when you press the "i need assistance" button on an airplane.

**Comment by nachiketkumar** [comment]
Good points. I also thought the wording was a little vague, and I had already changed it on my codepen to 'Help!' and 'I'm OK'. Perhaps when this is toggled, the flash message can make it clear what happens.

As it stands right now with the new changes from the pusher branch, as a student, I won't necessarily know what "Queue status changed successfully" means. A combination of a toggle and error message might work better:

Default is 'I'm OK'. 
- Click > Changes to 'Help!' and flash says "Your teacher has been notified that you need help."
- Click > Changes back to 'I'm OK' and flash says "You have been removed from the help queue."

Thoughts? This isn't addressing the technical feasibility of making the form submit or not. That could be the deciding factor.

**Comment by aomran** [comment]
I found the "I'm Ok" and "Help!" a bit confusing (it's pretty much what we had before the latest branch). After I add myself to the queue I see a button/link/checkbox that says "Help!", which sort of tells me that I should click it if I need help. I might be in the queue for days, so I might forget what my status really is. 

Maybe default => "I need help" (or something similar) and then "In help queue" after that. The flash can say what Nachi suggested. So:
- Click > Changes to 'In help queue' and flash says "Your teacher has been notified that you need help."
- Click > Changes back to 'I need help' and flash says "You have been removed from the help queue."

That way the link/button/checkbox message is the "action" you will perform and while in the queue the message says so.

**Comment by pjfranzini** [comment]
Again, having it say 'I need help' when you haven't asked for help is potentially confusing (it looks like a message that could be there because you have already asked for help). In queue/Not in queue (what it is in Ahmed's latest merged branch) is also confusing -- it shows your current status well, but (a) what is this queue? (b) how do I know that clicking on this will change my status?
How about starting out with "Ask for help" (or "Click for help") and then as Ahmed suggests above
Click > Changes to 'In help queue' and flash says "Your teacher has been notified that you need help."
Click > Changes back to 'Ask for help' and flash says "You have been removed from the help queue."

**Comment by pjfranzini** [comment]
Iconically, perhaps something to do with an airline call button -- perhaps not the symbol itself, but something of a button that looks "lit-up" when in queue, un-illuminated when not?

**Comment by nachiketkumar** [comment]
I like Paula's wording. I think that would make a lot of sense if styled appropriately.

Another reason for getting away with having it be links is that the page refreshes when the status is toggled by a student. They could be in the middle of answering how they feel for a particular track, and then want to ask for help. We are currently refreshing the page when this happens. Would preventing a refresh still submit the action?

If a checkbox can be used, I can work on styling it to look like a button. It would be one color (`$color-primary`?) when on 'Ask for Help' and a different color (`$color-success`?) and look like it's been pressed in when in `:checked` state. This is assuming a checkbox would work for our needs here. (Paula, your comment popped up after I had already written this- we're thinking on the same lines!)

If not, let me know what elements to use for styling this.

**Comment by aomran** [comment]
The browser doesn't refresh if we use ajax (was going to do that anyhow). It can gracefully degrade to a regular link/form if JavaScript is turned off. Whether we use a checkbox or button, a form needs to warp around it to make it work. So choose whichever is easier to work with.

**Comment by aomran** [comment]
As for the uservoice issue - there are a few options for the widget. There's a "SmartVote" option. The icon is a lightbulb, users can post a suggestion or send us an email. There's also the classic view which looks different. Have a look at the  options.

**Comment by nachiketkumar** [comment]
How does [this](http://codepen.io/nachiketkumar/pen/tIszx) look? The accompanying flash messages should clarify what has happened as discussed. I also added a title for the div, so if someone hovers on it and waits, they will see it. There's also a `:focus` state, as well as a glowing state for the `:checked` state.

I can add this in and let you wrap in a form and make it work?

I'll check out the uservoice options next.

**Comment by pjfranzini** [comment]
The button (and its various states and texts) looks good to me. One thing I would suggest, for an "In Help Queue", would be an "warning" red or orange color rather than a "calming" blue color.

**Comment by nachiketkumar** [comment]
I've changed it to a warning red color. However, what do you think about the connotation for the students? Are we telling them that asking for help is a bad thing? I wonder what the perception would be or if I'm overthinking it.

**Comment by pjfranzini** [comment]
Yeah, I thought of that after I posted it, that calming them if they were worried and therefore asking a question might not be so bad. But I would tend to think that we might be overthinking it thinking like that, and it would just be a question of having the being-in-queue stand out. Perhaps we can take the final decision after seeing how it looks on the page? or even do user analytics tests on it :)

**Comment by nachiketkumar** [comment]
So I'm having a weird problem with this styling in FF. I have the latest stable build (26.0) and the default 'Ask for Help' text is way off to the left. I couldn't figure out why this is happening but it seems to work on Webkit browsers as well as Opera. Can you replicate the probelm? Any thoughts?

**Comment by aomran** [comment]
Yep I see the problem in firefox.

**Comment by aomran** [comment]
Why not a simple button? Set the button's style with a class and render the button's text with ruby. The "add/remove" from queue is a toggle anyhow so the same button makes sense.

**Comment by nachiketkumar** [comment]
I don't totally understand why [this fork](http://codepen.io/nachiketkumar/pen/bHsJe) worked but it did, mostly. In FF the deault text isn't absolutely centered but otherwise works. 

I can try with a button, I don't want to spend too much more time on this. So the default class would show "Ask for Help"? And on clicking, we'd add a class through JS to change appearance?

Edit: Could you set up the code with a button and push a commit? I can then style it quickly.

**Comment by aomran** [comment]
For now don't worry about the JavaScript since I can do that later. In the help_toggle partial you can do:

``` irb
<% if current_user.needs_help?(@classroom) %>
  <%= link_to "In help queue", classroom_requester_path(classroom_id: @classroom.id, id: requester.id), method: :patch, class: 'help-button', id: 'in-help-queue' %>
<% else %>
  <%= link_to "Ask for help", classroom_requester_path(classroom_id: @classroom.id, id: requester.id), method: :patch, class: 'help-button', id: 'ask-for-help'  %>
<% end %>
```

So the `help-button` class includes the styles that both buttons share. Each button gets an id to set it's colour and unique look. The button's text is set through ruby. Change the `link_to` to `button_to` if you prefer a real button; this will add a button wrapped in a form.

**Comment by aomran** [comment]
When I add the JavaScript it will make an ajax request and on success it will add the appropriate id/class to the button and change the button's text. This is pretty easy to do.

**Comment by nachiketkumar** [comment]
I used classes only, hope that's OK. This should be ready for you to work your JS magic on and then merged.

**Comment by nachiketkumar** [comment]
The flash messaging shows the same message in both cases- why?

**Comment by aomran** [comment]
That's in the requesters controller update action. One would need to check the help status (true/false) and then set the notice appropriate. I can do it.

**Comment by Peak19** [comment]
I like the button that Nachi created on Codepen. I think a another logical colour choice might be a green glow when you've clicked to get in the queue. "Everything is going to be ok, you're in the line to get help"

At some future time, I also think it would be useful to introduce a queue number so students know where they are in the line. That way a teacher doesn't have to come looking for the student, a student would know to approach the teacher. 

An obvious graphic for me would be to have a solid circle indicating the teacher that becomes hollow when you click on it - as in a teacher is "open". Smaller grey dots would stretch out to the right of the central circle equalling the number of students in front of you. As students are dealt with the number of dots is reduced and the line shortens. When it is your turn to see the teacher the hollow circle glows green.

**Comment by aomran** [comment]
I'm going to work on the javascript for the teacher's header next. Let me know if there's anything else you need.

**Comment by aomran** [comment]
Both Paula and I have looked at this so merge whenever you want Nachi.

**Comment by nachiketkumar** [comment]
Done with this for now, all looks good with the polling :+1:

**Pull request merged**
