### PR TITLE
Styleguide

### PR DESCRIPTION
**Pull request by aomran**
Making a pull request so that we can keep discussions together in one place. This won't be merged until it's ready.

### CODE REVIEW

**Comment by aomran** [comment]
Looking great so far :)

**Comment by pjfranzini** [comment]
The style guide looks great!
The change you made in your second commit (to get only local styles to show) was one of the many variations I tried, and in fact even in your version they still appeared -- for me but I knew they hadn't for Ahmed -- but went away finally upon restart.
Should the example text (Header 1 etc) actually appear in Source Sans Pro?
I'd love to see the colors a bit darker and more saturated, and the orange a touch less red, and the red a touch less crimson:
$main-color: #415463;
$primary-color: #3D88FF;
$success-color: #00CB51;
$warning-color: #EDC028;
$danger-color: #F02810;
Aside from being purer accents of color, readability is also improved.

**Comment by nachiketkumar** [comment]
Yeah I think I just had to restart rails server- I guess if you make changes in the config files, you have to restart for it to take effect? I'll play with your color suggestions tomorrow- thanks!

As for the Headers- not sure I understand the question- they _should_ appear in Source Sans Pro in the example section- are they not? They are on my end.

**Comment by aomran** [comment]
The google fonts are imported in app/views/layouts/application.html.erb. I assume this means they are not imported for the style-guide. That could be the issue.

**Comment by pjfranzini** [comment]
For me (also on Ahmed's machine), on http://localhost:3000/style-guide/2_branding they do not; while on the main app pages (eg http://localhost:3000/login) they do. I add a g to be sure -- the closed bottom loop appears in the app but not in the styleguide typography examples. For us; maybe different on your machine because it knows the font?

Meanwhile Ahmed seems to have found the issue (see above).

Also, might make more sense for 
font-family: $sans-serif;
to be set in typography.css.scss than in styles_main.css.scss

**Comment by nachiketkumar** [comment]
Yup you are both correct- any ideas where to link those stylesheets so that they'd be available in the styleguide? Since it's an open source font, I have it on my system, and I can share it with you. Let me see if I can figure out how to fix this otherwise- I've been looking at the styleguide on my end entirely in source sans pro!

Paula, on this branch, the $sans-serif should be moved out of styles_main- I've moved all variables into _variables.scss; is that not the case for you? I want to do some reorganizing of the stylesheets in a more logical manner, which will be a next step soon.

**Comment by pjfranzini** [comment]
As I see it, the definition of $sans_serif is in _variables.scss; however it is referred to in styles_main.css.scss (the line font-family: $sans-serif; in the body def); I was suggesting that this reference might go well in typography.css.scss.

If this doesn't clear up what I mean, further comments are that in
https://github.com/aomra015/curri/commit/45020f7ae7590b33daf12e38f949fdf2ab982acd
I see you put the definition in app/assets/stylesheets/_variables.scss but the reference is still in
app/assets/stylesheets/styles_main.css.scss

As for having the font on my system, I guess I'd rather not -- it is not having the font that lets me see what might be user issues -- although admittedly right now the problem is not in a user area but in a developer area.

**Comment by aomran** [comment]
Instead of linking to the font just `@import` it in the typography CSS file. If you look in the Google font page you'll see that there are three options for including the font: html, css import and JavaScript.

**Comment by nachiketkumar** [comment]
Done- it works thanks. New commit should fix this.

Paula- I'm going to reorganize the stylesheets, probably early next week. I'm thinking of using a system either very similar to or derived from [Github's](https://github.com/styleguide/css) or [55 Minutes's](http://blog.55minutes.com/2013/01/smacss-and-rails/#styleguide) (also based on Githubs) File Organization systems. According to this, $sans-serif should go into a globals/_variables.scss file. Thoughts?

**Comment by nachiketkumar** [comment]
I have re-organized all the css files per the guidelines in our styleguide. It's borked some parts of the app but I'm not concerned since we're going to re-do most of it anyway. At least now the files are in their rightful places and the organization makes sense. More refactoring will be done as I go through the process of doing the new UI, and better understand the logic of SMACSS, but I feel like I'm at a good stage now. More information added to the styleguide too.

**Comment by pjfranzini** [comment]
re the $sans-serif, again, I agree the definition goes in _variables.scss, I was only talking about where you then use that definition. Anyhow a minor detail.

**Comment by nachiketkumar** [comment]
hahaha Paula- my bad..that's not what I meant to type! Yes, you are right, in this case after the re-organization, that $sans-serif would be used on body in the base.css.scss.

**Comment by aomran** [comment]
There was a merge conflict that I fixed between this branch and master.

**Comment by nachiketkumar** [comment]
what is the correct command I should be using for pulling your changes to this branch? I said `git pull` when on my local styleguide branch, but got a message saying "There is no tracking information for the current branch.
Please specify which branch you want to merge with." Saying `git pull origin styleguide` sent me into the vim editor interface, which always scares the crap out of me, and forced me to enter a merge message which I failed to do. Finally I had to do a separate `git commit -m "fix merge conflicts"`, which worked but I still don't know why I had to do that.

**Comment by aomran** [comment]
The `$ git pull origin styleguide` is the right way to do it. Note that the command says pull the branch `styleguide` from the remote called `origin` to the branch that I am currently in. `$ git pull` works in master because at some point we set the default to origin/master. 

When you are pulled into VI/VIM:
1. Press `Escape` -- just to make sure you're not in insert mode.
2. Press `Shift + :` to get a `:`.
3. Press `q`
4. Press `Enter`

It will kick you out and show that the merge happened. If there is a merge conflict then it will tell you which file is the issue. Just do `$ git status` to get this information again. Once you fix the file(s) you just need to add them with `$git add <file or files>` and then `$git commit` (without a message).

**Comment by pjfranzini** [comment]
So I'm confused and curious -- I was looking at the style-guide views, and wondering why the overview files were blank, even though there clearly is Curri-specific content in section 1. I tracked down the content to Config/locales/en.yml, and was curious why it's done that way.

**Comment by nachiketkumar** [comment]
I can't answer _why_ it's done that way- but the instructions in pivotal's wiki said to do it that way. Any documentation that goes in the part above the example section must go in the en.yml file, and the actual example code goes in the partial that lives in views/style-guide/. The Overview partials are just documentation really, with no example code so to speak, so I put the documentation in the en.yml file. Also, no idea why there are merge conflicts again in this branch- how do I see what is causing the conflicts?

**Comment by pjfranzini** [comment]
ok ty for the explanation.
for the merge conflicts, Ahmed added more gems etc, he says git status after an attempted merge should tell you what is in conflict, and that it is probably the gemfile. He'll write you some more info.

**Comment by nachiketkumar** [comment]
Sounds good. Still trying to understand why this time when I did `git pull origin styleguide` after Ahmeds commit above, there were no issues. Didn't send me into VI or ask me to do a merge. I have the new gems and all other changes on my local branch. Ah Git....

**Comment by aomran** [comment]
We merged a branch into master called "DevImprove". We'll keep branching and merging into master so chances are this branch will need merge conflicts resolved every now and then. Ideally we make small branches and merge into master ASAP. These big branches should be kept to a minimum. 

I fixed the merge conflicts but I'll explain how so that anyone can do it.
1. Update your local "master" branch.
2. Switch to your local "styleguide" branch and make sure it's up to date.
3. `$git merge master` to try to merge master into the "styleguide" branch.
4. It will say something like `CONFLICT (content): Merge conflict in <file>`.
5. Do `$ git status` to see all merge conflicts. Look for a red label that says `both modified: <filename>` to see where merge conflicts are. In the above merge conflict it was listing Gemfile and Gemfile.lock.
6. Open up the file where it says there's a merge conflict. You will see something like this:
   
   ```
   <<<<<<< HEAD
   gem "rack-livereload", group: "development"
   gem "guard-livereload", group: "development"
   =======
   group :development do
     gem 'brakeman', :require => false
     gem 'better_errors'
     gem 'binding_of_caller'
     gem 'meta_request'
     gem 'rails_best_practices'
     gem 'bullet'
   end
   >>>>>>> master
   ```
   
   The `<<<<<<< HEAD` to `=======` are the contents of the current HEAD branch. The `=======` to `>>>>>>> master` are the contents of the master branch. Get rid of these markers, choosing to keep one version or the other (or both). In this case I kept both since there is really no merge conflict - we just modified the same file. `Gemfile.lock` is usually really hard to clean up so delete it and `$ bundle install` to get a fresh version.
7. `$ git add -A`
8. `$ git commit`  ==> don't add a message unless you really want to.
9. You will go into VI/VIM so be ready to exit it with `:q` and `Enter`.

**Comment by aomran** [comment]
And I'm not sure why it had you do a merge last time Nachi.

**Comment by pjfranzini** [comment]
I've copied Ahmed's explanation into our Wiki for easy reference.

**Comment by nachiketkumar** [comment]
I'm close to being done with the styleguide- the last major section left is the grid. Anything else you think needs to be addressed here? What do you think the process should be for merging this into master? It's going to break a fair amount of the styles, but that can't be helped. The next step after that would be go into the views and apply the correct structure and classes there.

**Comment by aomran** [comment]
I don't think that breaking the views is an issue. Or you can branch off of
the style guide branch. Merge this new branch into style guide then into
master.

**Comment by Peak19** [comment]
I guys, I haven't gone into great detail regarding the stylesheet but I really like the direction its going. The buttons are totally cool. I didn't realize you could have a flat 3d look. I also like the colours. They could be more saturated but with a screen filled with bright analytics reducing their punchiness might be preferable. I'd like to see how it plays out in the restyled app.

**Comment by nachiketkumar** [comment]
Ali, thanks for the feedback. I share the same concerns with Ali re more saturated colors, and I can imagine the student checkpoints page looking like a rainbow if the colors are too strong. Considering the fact that there is very little other color in the app, even less saturated colors should stand out enough. I am going to put Paula's color suggestions in as commented out variables, so that when we have the app restyled, we can switch colors easily and see how the more saturated colors look in context.

**Comment by pjfranzini** [comment]
Yes it would be best to decide after seeing it in context. And maybe a smaller nudge would be better.

**Comment by aomran** [comment]
It might be a good idea to wrap up this branch and merge it into master. That way we don't have to keep updating this branch when master updates.

**Comment by nachiketkumar** [comment]
OK, I think I'm done with this for the time being- the large chunks have been worked on and I can add on to the styles that will be more module related as I work on the views. If this build passes on Semaphore, this can be merged into master. 

Beware that the layout is going to be destroyed, but hopefully with my notes from the Layout section of the styleguide, it should not be too difficult to start putting things together quickly. For now, I have commented out older styles, so they are still there for reference.

**Pull request merged**
